Task 8 testing with client
VasiaBirchak/myblog_Byrchak_Vasyl pull request #23
Opened 2024-05-31 12:12 UTC by VasiaBirchak

2024-05-31 12:13 UTC, VasiaBirchak commented
Is it ok if my test_logout_page: Tests that a 302 status code is returned after the logout is done because a redirect happens after a successful logout?

2024-05-31 17:52 UTC, ejariza-evowill requested changes

2024-05-31 17:52 UTC, ejariza-evowill commented on myblog/blog/tests/test_views.py
> +        assert response.status_code == 200
Dont check only status code, check here for example that user was logged in.

2024-06-03 12:45 UTC, VasiaBirchak commented
Done the tests

2024-06-03 17:52 UTC, ejariza-evowill requested changes

2024-06-03 17:52 UTC, ejariza-evowill commented on myblog/blog/tests/test_views.py
> +        assert response.status_code == 302
for redirections you can use the `follow=True`, parameter in in client calls

2024-06-04 02:02 UTC, ejariza-evowill approved these changes

2024-06-05 17:19 UTC, merged