Task 9 djangorest
VasiaBirchak/myblog_Byrchak_Vasyl pull request #24
Opened 2024-06-03 17:55 UTC by VasiaBirchak

2024-06-03 18:17 UTC, ejariza-evowill requested changes

2024-06-03 18:17 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +        fields = ['title', 'body', 'author']
As this is not going to change during runtime change it to tuples.

2024-06-03 18:17 UTC, ejariza-evowill commented on myblog/blog/test_rest.py
> +        BlogPost.objects.create(title='Post 3', body='Body of post 3', author=self.user)
This can be a comprehension list

2024-06-03 18:45 UTC, VasiaBirchak commented on myblog/blog/test_rest.py
> +        BlogPost.objects.create(title='Post 3', body='Body of post 3', author=self.user)
Good idea

2024-06-03 18:45 UTC, VasiaBirchak commented on myblog/blog/api/serializers.py
> +        fields = ['title', 'body', 'author']
Thank you, this is a good solution

2024-06-03 18:53 UTC, ejariza-evowill commented
Remember to run flake8 command locally so you can see style errors before you push

2024-06-03 19:02 UTC, VasiaBirchak commented
Sorry, I forgot about the flake and remembered it only after I pushed it, I just wanted to change it and you already added a comment)

2024-06-04 01:53 UTC, ejariza-evowill approved these changes

2024-06-05 17:19 UTC, merged