Task 14 representing relations
VasiaBirchak/myblog_Byrchak_Vasyl pull request #29
Opened 2024-06-07 16:36 UTC by VasiaBirchak

2024-06-07 23:23 UTC, ejariza-evowill requested changes

2024-06-07 23:23 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +        fields = '__all__'
don't use `__all__`, instead put the name of all fields that you're going to use in this serializer.

Remember: _explicit is better than implicit._

2024-06-07 23:23 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +        fields = '__all__'
Same here

2024-06-07 23:23 UTC, ejariza-evowill commented on myblog/blog/tests/test_comment.py
> +class TestCommentModel(TestCase):
Once again, stick to use `pytest`. `TestCase` is from `unittest`

2024-06-07 23:23 UTC, ejariza-evowill commented on myblog/blog/tests/test_comment.py
> +        self.post = BlogPost.objects.create(title='Test Post', body='Test Body', author=self.user)
These should be fixtures as well.

2024-06-07 23:23 UTC, ejariza-evowill commented on myblog/blog/views.py
> +class CommentRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
These two classes are identical, Why don't making a single one that inherits from `ModelViewSet`?

2024-06-11 17:45 UTC, ejariza-evowill requested changes

2024-06-11 17:45 UTC, ejariza-evowill commented on myblog/blog/urls.py
> +router.register(r'api/comments', views.CommentViewSet, basename='comment')
Keep consistency here, whether you import both viewsets from views or only import views, in other words, adapt one of this styles:

```python
router.register(r'api/post', views.PostViewSet, basename='post')
# or
router.register(r'api/comments', CommentViewSet, basename='comment')
```

2024-06-12 19:25 UTC, VasiaBirchak commented on myblog/blog/urls.py
> +router.register(r'api/comments', views.CommentViewSet, basename='comment')
ok. I understand

2024-06-12 22:14 UTC, ejariza-evowill approved these changes

2024-06-12 22:15 UTC, ejariza-evowill commented
Before proceeding with new tasks, fix conflicts here and merge,

2024-06-13 16:14 UTC, merged