Task 15 other type of fields
VasiaBirchak/myblog_Byrchak_Vasyl pull request #30
Opened 2024-06-12 22:11 UTC by VasiaBirchak

2024-06-12 22:18 UTC, ejariza-evowill requested changes

2024-06-12 22:18 UTC, ejariza-evowill commented on myblog/media/uploads/images/2024/06/12/ancient-ruins.png
Remove this file as it is a test file, also make sure that you exclude everything from the `uploads` dir in `.gitignore`.

2024-06-13 13:17 UTC, VasiaBirchak commented on myblog/media/uploads/images/2024/06/12/ancient-ruins.png
of course I will fix it. I didn't notice that it was uploaded to a remote repo. I kept it in my head until the last and didn't check it in the end :(

2024-06-14 22:43 UTC, ejariza-evowill approved these changes

2024-06-19 13:02 UTC, merged