Task 17 dry
VasiaBirchak/myblog_Byrchak_Vasyl pull request #32
Opened 2024-06-19 16:21 UTC by VasiaBirchak

2024-06-19 18:52 UTC, ejariza-evowill requested changes

2024-06-19 18:52 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +                UserTag.objects.create(post=instance, user=user)
Why do you think this is necessary to do?

2024-06-19 18:52 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +            instance.tagged_users.all().delete()  # видалити старі теги
In general avoid letting comments in languages different than english, not only they can confuse other developers, but in some systems the non-standard characters can cause problems.

2024-06-19 18:52 UTC, ejariza-evowill commented on myblog/blog/models.py
> +    # tagged_users = models.ManyToManyField(User, through='UserTag', related_name='tagged_posts')
remove commented code

2024-06-20 10:40 UTC, VasiaBirchak commented on myblog/blog/api/serializers.py
> +                UserTag.objects.create(post=instance, user=user)
instance.tagged_users.all().delete()
This removes all old tags associated with the post. If the list of users who tagged a post has changed, the old tags will not remain in the database.
UserTag.objects.create(post=instance, user=user)
This creates new entries in the tags table for each user that should now be associated with the post.
Correct me if I'm wrong.

2024-06-20 10:42 UTC, VasiaBirchak commented on myblog/blog/api/serializers.py
> +            instance.tagged_users.all().delete()  # видалити старі теги
Sorry for that, I sometimes leave a comment for better understanding when I create something. I will avoid them in the future)

2024-06-20 15:30 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +                UserTag.objects.create(post=instance, user=user)
Ok, I'll approve it because it make sense, but this is not the best strategy because you are deleting all tags and recreating every time, it would be better, if you allow updates on tagged users on this method, to check the differences and only create/destroy these which correspond.

2024-06-20 15:30 UTC, ejariza-evowill approved these changes

2024-06-24 13:03 UTC, merged