Task 18 filter
VasiaBirchak/myblog_Byrchak_Vasyl pull request #33
Opened 2024-06-19 16:22 UTC by VasiaBirchak

2024-06-19 19:09 UTC, ejariza-evowill requested changes

2024-06-19 19:09 UTC, ejariza-evowill commented on myblog/myblog/settings.py
> +    # ),
remove commented code

2024-06-20 10:52 UTC, VasiaBirchak commented on myblog/blog/views.py
> +            tagged_posts = [user_tag.post for user_tag in user_tags]
Ok, thank you

2024-06-20 15:33 UTC, ejariza-evowill approved these changes

2024-06-24 13:03 UTC, merged