Task 19 like
VasiaBirchak/myblog_Byrchak_Vasyl pull request #34
Opened 2024-06-20 14:15 UTC by VasiaBirchak

2024-06-20 15:54 UTC, ejariza-evowill requested changes

2024-06-20 15:54 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
> +    likes = LikeSerializer(many=True, read_only=True)
If a post have many likes, this can cause performance problems, consider bringing better a `likes_count`

2024-06-20 15:54 UTC, ejariza-evowill commented on myblog/blog/tests/test_likes.py
> +    response = client.post(f'/blog/api/post/{test_post.id}/unlike/')
Check also that there existed a like before.

2024-06-20 15:54 UTC, ejariza-evowill commented on myblog/blog/views.py
> +    @action(detail=True, methods=['post', 'get'], permission_classes=[IsAuthenticated])
Let's make all these `like`/`unlike` actions only allow `post` method.

2024-06-24 13:37 UTC, VasiaBirchak commented on myblog/blog/views.py
> +    @action(detail=True, methods=['post', 'get'], permission_classes=[IsAuthenticated])
I have some trouble with this. When I leave only a method 'post', I cannot manually like or unlike it. The tests can pass, but manual i can't make any actions , and I don't know how to change it.
<img width="593" alt="Знімок екрана 2024-06-24 о 16 31 31" src="https://github.com/VasiaBirchak/myblog_Byrchak_Vasyl/assets/57287636/5ecf24fa-cd39-4c9b-b776-bd9dc8832bdb">

2024-06-24 19:10 UTC, ejariza-evowill commented on myblog/blog/views.py
> +    @action(detail=True, methods=['post', 'get'], permission_classes=[IsAuthenticated])
fot testing a post manually you can make a [curl request.](https://www.geeksforgeeks.org/curl-command-in-linux-with-examples/)

2024-06-24 19:12 UTC, ejariza-evowill approved these changes

2024-06-26 12:34 UTC, merged