Task 22 redis
VasiaBirchak/myblog_Byrchak_Vasyl pull request #37
Opened 2024-07-02 10:07 UTC by VasiaBirchak

2024-07-02 17:24 UTC, ejariza-evowill requested changes

2024-07-02 17:24 UTC, ejariza-evowill commented on myblog/blog/api/serializers.py
>  class LikeSerializer(serializers.ModelSerializer):
I don't think you need a `LikeSerializer`.

2024-07-04 08:10 UTC, VasiaBirchak commented on myblog/blog/api/serializers.py
>  class LikeSerializer(serializers.ModelSerializer):
Yes, sure

2024-07-04 19:18 UTC, ejariza-evowill requested changes
Your test are failing because you are not mocking redis correctly

2024-07-08 18:16 UTC, ejariza-evowill approved these changes

2024-07-09 22:21 UTC, merged